### ISSUE TITLE
New tcsh release

### ISSUE THREAD

**Issue by mepholic** [tcsh-org/tcsh#12]
Is there going to be a new release of tcsh any time soon? There hasn't been a release in about 3 years, and considering some of the helpful fixes in `master` since then, it would be nice if we could see another release 😃

Many distributions ship tcsh as a shell choice, and as a package maintainer of tcsh in a couple of them, I generally consider it bad practice to ship packages from `master`/`development` branches and generally like to work with a tagged release, or a release tarball.

Are there any urgent outstanding issues that would cause you to deem the current `HEAD` commit unstable, or unfit for production usage?

**Comment by ghost** [comment]
I would also like a new release.

mepholic <notifications@github.com> 于 2019年4月26日周五 18:23写道：

**Comment by zoulasc** [comment]
On Apr 26,  6:21am, notifications@github.com (Lockywolf) wrote:
-- Subject: Re: [tcsh-org/tcsh] New tcsh release (#12)

| I would also like a new release.

Ok, let's do it then. Are there any regressions that we know of?
I don't think it is wise to attempt to fix any of the bugs in the
mantis database https://bugs.astron.com/ since we will not have time
to test them properly.

christos

**Comment by zoulasc** [comment]
On Apr 26 10:04, Christos Zoulas wrote:
> On Apr 26,  6:21am, notifications@github.com (Lockywolf) wrote:
> -- Subject: Re: [tcsh-org/tcsh] New tcsh release (#12)
> 
> | I would also like a new release.
> 
> Ok, let's do it then. Are there any regressions that we know of?

Just trying to build on Cygwin I get:

ed.inputl.c:668:1: error: conflicting types for ‘GetCmdChar’
 GetCmdChar(wchar_t ch)
 ^~~~~~~~~~
In file included from ed.h:230:0,
                 from ed.inputl.c:33:
ed.decls.h:252:12: note: previous declaration of ‘GetCmdChar’ was here
 extern int GetCmdChar  (Char);
            ^~~~~~~~~~
make: *** [Makefile:463: ed.inputl.o] Error 1

So thats Char vs. wchar_t for the argument.  What's right?


Thanks,
Corinna

-- 
Corinna Vinschen
Cygwin Maintainer
Red Hat

**Comment by amoldeshpande** [comment]
couldn't send to the mailing list for some reason, but I'm not able to get savedirs to work on Ubuntu 18.04

Haven't used Linux regularly in ages, so I'm not sure if I'm missing something

output of set:
savedirs	100
savehist	(200 merge)
shell	/bin/tcsh

output of echo $version

tcsh 6.20.00 (Astron) 2016-11-24 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,nd,color,filec

output of uname -a

Linux  <hostname> 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

I open a terminal, CD to a dir, and exit. when I start another terminal, it starts back at my home directory.

**Comment by zoulasc** [comment]
I've got a small and simple addition it may be worth adding first,
I'll post it in a new email.

cheers, Jamie

**Comment by zoulasc** [comment]
With many command line utilities now using two words for the command
(e.g. "pkg", "gpart", "svn", "git", "zfs", "zpool" etc). I've found
it useful to be able to base completion rules on the value of the
first parameter.

Your currently have 'c', 'C', 'n', 'N', 'p' etc.  I propose adding 'f'
(for "first").

Then you can have such constructs as:

complete pkg 'f|help|`tcsh-completions cmdlist`|' 'f|add|`tcsh-completions add`|' 'f|which|`tcsh-completions which`|' 'f|{fetch,install,search}|`tcsh-completions search`|'
 
.. for coping with commands like "pkg help", "pkg add" etc.

I include a patch below.. Whilst at it, I also added options '1' to '5'
to match the specific numbered parameters (obviously, '1' is the same as
'f') - I thought it may be useful, however, I've not found a use to date.

I've been running this for a few months now.

Could something like this (at least the 'f' option [I don't care if you'd
prefer to assign a different letter for it]) be added? It would be
useful as more and more programs are being released which use this "2
word command" syntax.

If accepted, I'll patch the manpage accordingly.

Cheers, Jamie

--- tcsh/tw.comp.c.orig	2017-04-15 12:13:11.420158000 +0100
+++ tcsh/tw.comp.c	2019-01-10 09:23:36.666850000 +0000
@@ -542,6 +542,22 @@
 	case 'n':
 	    pos = (wordno < 2) ? nomatch : wl[wordno - 2];
 	    break;
+	case 'f':
+	case '1':
+	    pos = wl[1];
+	    break;
+	case '2':
+	    pos = (wordno < 3) ? nomatch : wl[2];
+	    break;
+	case '3':
+	    pos = (wordno < 4) ? nomatch : wl[3];
+	    break;
+	case '4':
+	    pos = (wordno < 5) ? nomatch : wl[4];
+	    break;
+	case '5':
+	    pos = (wordno < 6) ? nomatch : wl[5];
+	    break;
 	case 'c':
 	case 'C':
 	    pos = (wordno < 1) ? nomatch : wl[wordno - 1];
@@ -617,6 +633,12 @@
 
 	case 'N':			/* match with the next-next word */
 	case 'n':			/* match with the next word */
+	case 'f':			/* match with the first word */
+	case '1':			/* match with the first word */
+	case '2':			/* match with the second word */
+	case '3':			/* match with the third word */
+	case '4':			/* match with the fourth word */
+	case '5':			/* match with the fifth word */
 	    exact = 1;
 	    /*FALLTHROUGH*/
 	case 'c':			/* match with the current word */

**Comment by Jamie-Landeg-Jones** [comment]
Oops, those last 2 messages were from me, but as I replied to the mailing list, I inadvetantly used Christos'  "golden github reply" email address.

Cheers, jamie

**Comment by zoulasc** [comment]
Having -[1-5] is fine but why do we also need -f that does the same as -1?

**Comment by Jamie-Landeg-Jones** [comment]
You're right. I originally went with 'f', and then added the more generic '1-X' later on, which I personally never used.

I included the 2 forms as an option. "f" is not needed if you choose to accept '1-X' - that's no probem. I just left it there as an option in case you didn't want to use "1-X (as at least "f" fits more cleanly into the current syntax)

But yeah, the "1-X' format is used, no need for "f".

Sorry for not clarifying.

Cheers!

**Comment by Jamie-Landeg-Jones** [comment]
You're right. I originally went with 'f', and then added the more generic '1-X' later on, which I personally ended up never using!

"f" is not needed if you choose to accept '1-X' - that's no problem. I just left it there as an option in case you didn't think "1-X" was worth adding. (as at least "f" fits more cleanly into the current syntax)

But yeah, if the "1-X' format is fine, there is no need for "f".

Sorry for not clarifying.

Cheers!

**Comment by zoulasc** [comment]
Something Ubuntu specific? I just tried it on NetBSD and it works.

**Comment by amoldeshpande** [comment]
I have to set the terminal preferences to launch tcsh as a login shell.  I guess I never gave it much thought because I always run tcsh -l in windows, an ingrained habit probably because of this behavior, but I can't remember any more.

**Comment by zoulasc** [comment]
New release has been done, let's move the conversation about the login shell to the mailing list.
